# Generated by Django 4.2.6 on 2023-10-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pdw',
            new_name='pwd',
        ),
    ]
