# Generated by Django 4.2.6 on 2023-12-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appointment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='user',
            name='appointmentFk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
