# Generated by Django 4.2.6 on 2023-12-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appointment_client_user_appointmentfk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointmentFk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
        ),
    ]
