# Generated by Django 4.2.6 on 2023-12-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_appointmentfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='appointmentFk',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AppointmentInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
